require('base')
require('plugins')
require('maps')
require('colorscheme')
require("plugin-config.nvim-tree")
require("plugin-config.telescope")
require("plugin-config.dashboard")
require("plugin-config.nvim-treesitter") 
-- require("lsp.setup")
-- require("lsp.cmp")
